### ISSUE TITLE
Zendesk reference

### ISSUE THREAD

**Issue by dimoschi** [fivetran/dbt_stripe#14]
https://github.com/fivetran/dbt_stripe/blob/0fca4f35a333187953443f03bdcf323c1dc77ecf/dbt_project.yml#L17-L30

Could this be correct referencing zendesk inside dbt_stripe repo?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dimoschi thanks for opening this issue!

You are correct, that is incorrect zendesk referencing and must be changed to stripe. I will open a PR to fix this today. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dimoschi, thank you again for catching this issue!

I have since been able to merge the PR mentioned above and cut the new `v0.4.1` release for the Stripe package which includes the updates. The release should be live on the dbt hub come Monday.

I will close the Issue as we have been able to implement the quick bug fix. Please feel free to reach back out if you have any further questions.

**Comment by dimoschi** [comment]
Thank you for the immediate response.
