### ISSUE TITLE
BUG - Unneeded `order by`s reduce performance

### ISSUE THREAD

**Issue by MarkMacArdle** [fivetran/dbt_stripe#16]
**Are you a current Fivetran customer?** 

Yes, Mark MacArdle, data engineer at Bought By Many.

**Describe the bug**

Most of the cleaned tables end with an order by (eg `stripe__balance_transactions.sql`). Ordering is an expensive operation but it won't be retained when users query the table. As it doesn't add anything the ordering should be removed.

**Steps to reproduce**
Look at the queries in the models folder.

**Package Version**

0.4.1

**Please indicate the level of urgency** 

Very low

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this @MarkMacArdle!

I completely agree with your Issue and PR changes and have since merged your PR with master. I am currently going to hold off cutting release `v0.4.2` for the time being as we are currently working on Issue #12 this sprint and are planning to batch the updates together in the next release.

As such, I will hold off closing this ticket until we have cut the new release. I will post here once we have. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@MarkMacArdle this has been adding to our recent `v0.4.2` release of the dbt_stripe package!!

This release will most likely be live on the dbt hub by Monday morning. Closing this ticket as the feature request has been integrated into the package. Please feel free to reach back out or create a new ticket if you have any further questions or requests.
