### ISSUE TITLE
[Feature] currency field to be pulled through to invoice_line_items

### ISSUE THREAD

**Issue by ccbrandenburg** [fivetran/dbt_stripe#46]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

We are charging multiple currencies through our stripe account and the invoice_line_items table does not have the `currency` field propagated through, even though it is available in upstream models.

Would it be sensible to include this?

### Describe alternatives you've considered

The alternative solution I see would be to join one of the tables like `balance_transactions` or `stg_stripe__fees` to `invoice_line_items` in our core models.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ccbrandenburg thanks so much for opening this feature request. I would agree with you that it would be beneficial to incorporate the `currency` field into the `stripe__invoice_line_items` end model. 

As you pointed out, this field is available in the upstream models and wouldn't be too difficult to incorporate in the end model. I notice you are interested in contributing this feature to the package! If you would like, this would be a great feature request to open a PR to incorporate within the package. If you open a PR, my team and I will be happy to review and work with you to get the PR in a place to merge into the next release.

If you are interested in opening a PR, let me know if you have any questions as I would be happy to help answer any. Otherwise, my team can pick this feature up in a future update down the line. 😄

**Comment by ccbrandenburg** [comment]
Hey @fivetran-joemarkiewicz happy to create a PR for this. 

I just tried to push my commits on my branch but seem to be missing permissions. Do you need to grant me permissions to push to the repo?

Any local testing I need to do or does it all run as part of the CI process?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ccbrandenburg you will need to fork this repo and make the changes to your fork. Once your local changes look good you can open a PR to this `main` branch on this repo! 

If you can do some local testing that would be great. The CI process will kick off regardless once we merge this into our repo.

**Comment by fivetran-reneeli** [comment]
Closing this issue out as the currency field is now incorporated in our invoice models!
